const { profileData, Auction } = require("../models");
const db = require("../config/connection");
const auctionSeeds = [
  { 
    itemName: "Among Us Nugget",
    description: "rare nugget from BTS collab",
    image: "https://res.cloudinary.com/ddtqwizaf/image/upload/v1623718837/yikes_eh7ujm.jpg",
    category: "Accessories",
    brand: "Unknown",
    seller: null,
    created: new Date(Date.now()).toISOString(),
    bidStart: new Date(Date.now()).toISOString() ,
    bidEnd: new Date(new Date().setDate(new Date().getDate() + 30)).toISOString(), // I HATE THIS SO MUCH WHAT IS THIS!!!!
    bids: [],
  },
  {
    itemName: "Y-3 High Tops",
    description: "Rare Y-3 Hong Kong shoes",
    image: "https://res.cloudinary.com/ddtqwizaf/image/upload/v1628603585/IMG_1289_hhrn7w.jpg",
    category: "Shoes",
    brand: "Y-3",
    seller: null,
    created: new Date(Date.now()).toISOString(),
    bidStart: new Date(Date.now()).toISOString(),
    bidEnd: new Date(new Date().setDate(new Date().getDate() + 30)).toISOString() ,
    bids: [],
  },
  {
    itemName: "Bird",
    description: "Bird, It's just a bird.",
    image: "https://res.cloudinary.com/theplugselect/image/upload/v1623709442/ywg1n19nnuetghwdv4ib.jpg",
    category: "Bird",
    brand: "Fucking Bird",
    seller: null,
    created: new Date(Date.now()).toISOString(),
    bidStart: new Date(Date.now()).toISOString() ,
    bidEnd: new Date(new Date().setDate(new Date().getDate() + 30)).toISOString()   ,
    bids: [],
  },
  {
    itemName: "Off-White Moto-Wrap",
    description: "A little worn, still near-mint",
    image: "https://res.cloudinary.com/ddtqwizaf/image/upload/v1623718839/offwhiteshoes_cmxsyk.jpg",
    category: "Shoes",
    brand: "Off-White",
    seller: null,
    created: new Date(Date.now()).toISOString(),
    bidStart: new Date(Date.now()).toISOString() ,
    bidEnd: new Date(new Date().setDate(new Date().getDate() + 30)).toISOString() ,
    bids: [],
  },
  {
    itemName: "Off-White Galaxy Hoodie",
    description: "Bruh, These are dope.",
    image: "https://res.cloudinary.com/ddtqwizaf/image/upload/v1623718857/offwhitegalaxy_wii4hp.jpg",
    category: "Outerwear",
    brand: "Off-White",
    seller: null,
    created: new Date(Date.now()).toISOString() ,
    bidStart: new Date(Date.now()).toISOString() ,
    bidEnd: new Date(new Date().setDate(new Date().getDate() + 30)).toISOString() ,
    bids: [],
  },
  {
    itemName: "Phenex Gundam Mastermind",
    description: "New, Not opened",
    image: "https://res.cloudinary.com/ddtqwizaf/image/upload/v1623718857/phenex_scb1um.jpg",
    category: "Collectibles",
    brand: "Mastermind",
    seller: null,
    created: new Date(Date.now()).toISOString() ,
    bidStart: new Date(Date.now()).toISOString() ,
    bidEnd: new Date(new Date().setDate(new Date().getDate() + 30)).toISOString() ,
    bids: [],
  },
  {
    itemName: "Off-White Alien Shirt",
    description: "New with tags",
    image: "https://res.cloudinary.com/ddtqwizaf/image/upload/v1623718856/offwhitealien_regjfq.jpg",
    category: "Shirts",
    brand: "Off-White",
    seller: null,
    created: new Date(Date.now()).toISOString() ,
    bidStart: new Date(Date.now()).toISOString() ,
    bidEnd: new Date(new Date().setDate(new Date().getDate() + 30)).toISOString() ,
    bids: [],
  },
  {
    itemName: "Balenciaga Shoes",
    description: "Only wore a little bit",
    image: "https://res.cloudinary.com/ddtqwizaf/image/upload/v1623718839/balenciagashoes_w1oqji.jpg",
    category: "Shoes",
    brand: "Balenciaga",
    seller: null,
    created: new Date(Date.now()).toISOString() ,
    bidStart: new Date(Date.now()).toISOString() ,
    bidEnd: new Date(new Date().setDate(new Date().getDate() + 30)).toISOString() ,
    bids: [],
  },
  {
    itemName: "Off-White Jacket",
    description: "Reflective Jacket",
    image: "https://res.cloudinary.com/ddtqwizaf/image/upload/v1623718858/offwhitemonclear_ebb4ey.jpg",
    category: "Outerwear",
    brand: "Off-White",
    seller: null,
    created: new Date(Date.now()).toISOString(),
    bidStart: new Date(Date.now()).toISOString(),
    bidEnd: new Date(new Date().setDate(new Date().getDate() + 30)).toISOString(),
    bids: [],
  },
  {
    itemName: "Off-White Shoes",
    description: "Used. Testing ground",
    image: "https://res.cloudinary.com/ddtqwizaf/image/upload/v1623718855/offwhiteshoes2_a7anr9.jpg",
    category: "Shoes",
    brand: "Off-White",
    seller: null,
    created: new Date(Date.now()).toISOString(),
    bidStart: new Date(Date.now()).toISOString(),
    bidEnd: new Date().setDate(new Date().getDate() + 30),
    bids: [],
  },
  {
    itemName: "Getter Bear Brick",
    description: "Super Robot bear brick collab",
    image: "https://res.cloudinary.com/ddtqwizaf/image/upload/v1628448858/medicom-toy-getter-robot-bearbrick-400-limited-edition-01_be7fca.jpg",
    category: "Collectibles",
    brand: "Bear Brick",
    seller: null,
    created: new Date(Date.now()).toISOString(),
    bidStart: new Date(Date.now()).toISOString(),
    bidEnd: new Date(new Date().setDate(new Date().getDate() + 30)).toISOString(),
    bids: [],
  },
  {
    itemName: "Bape Rx-78-2 Gundam MG",
    description: "Gundam X Bape Collab, new in box",
    image: "https://res.cloudinary.com/ddtqwizaf/image/upload/v1628448946/3__79362.1607094545_ay6i5w.jpg",
    category: "Collectibles",
    brand: "Bape",
    seller: null,
    created: new Date(Date.now()).toISOString(),
    bidStart: new Date(Date.now()).toISOString(),
    bidEnd: new Date(new Date().setDate(new Date().getDate() + 30)).toISOString(),
    bids: [],
  },
  {
    itemName: "Y-3 Suika Shoes",
    description: "In good condition",
    image: "https://res.cloudinary.com/ddtqwizaf/image/upload/v1628449341/310_oxqojj.jpg",
    category: "Shoes",
    brand: "Y-3",
    seller: null,
    created: new Date(Date.now()).toISOString(),
    bidStart: new Date(Date.now()).toISOString(),
    bidEnd: new Date(new Date().setDate(new Date().getDate() + 30)).toISOString(),
    bids: [],
  },
  {
    itemName: "Toyota Char Edition",
    description: "It's 3 times as fast.",
    image: "https://res.cloudinary.com/ddtqwizaf/image/upload/v1628449340/bd6b75c8f8952b6ab149df9378ad63ee_mv0zg7.jpg",
    category: "Collectibles",
    brand: "Toyota",
    seller: null,
    created: new Date(Date.now()).toISOString(),
    bidStart: new Date(Date.now()).toISOString(),
    bidEnd: new Date(new Date().setDate(new Date().getDate() + 30)).toISOString(),
    bids: [],
  },
  {
    itemName: "KTZ Jacket",
    description: "Only wore it a few times",
    image: "https://res.cloudinary.com/ddtqwizaf/image/upload/v1628449340/15057567_27262564_600_kjoelk.webp",
    category: "Outerwear",
    brand: "KTZ",
    seller: null,
    created: new Date(Date.now()).toISOString(),
    bidStart: new Date(Date.now()).toISOString(),
    bidEnd: new Date(new Date().setDate(new Date().getDate() + 30)).toISOString(),
    bids: [],
  },
  {
    itemName: "Mastermind Rx-78-2 Gundam",
    description: "Mastermind human size gundam",
    image: "https://res.cloudinary.com/ddtqwizaf/image/upload/v1628449654/untitled-78_f1r3vz.jpg",
    category: "Collectibles",
    brand: "Mastermind",
    seller: null,
    created: new Date(Date.now()).toISOString(),
    bidStart: new Date(Date.now()).toISOString(),
    bidEnd: new Date(new Date().setDate(new Date().getDate() + 30)).toISOString(),
    bids: [],
  },
  {
    itemName: "KAWS Dissected Statue",
    description: "Rare statue",
    image: "https://res.cloudinary.com/ddtqwizaf/image/upload/v1628449757/kaws-4ft-dissected-companlon-kaws-1-3m-anatomy_hlmbnk.jpg",
    category: "Collectibles",
    brand: "KAWS",
    seller: null,
    created: new Date(Date.now()).toISOString(),
    bidStart: new Date(Date.now()).toISOString(),
    bidEnd: new Date(new Date().setDate(new Date().getDate() + 30)).toISOString(),
    bids: [],
  },
];

const seedAuctions = async () => {
  try {
    await Auction.deleteMany({});
    const users = await profileData.find({});
    const auctions = await Auction.insertMany(auctionSeeds);
      console.log(auctions);
      console.log(users);
    for (let auction of auctions) {
      const tempUser = users[Math.floor(Math.random() * users.length)]; // random user to assign as the seller
      auction.seller = tempUser._id;
      // await to save the auction
      await auction.save();
      console.log(auctions)
    }
    return;
  } catch (err) {
    return;
  }
};

module.exports = { seedAuctions };
