export {default as Home} from './Home/Home';
export {default as About} from './About/About';
export {default as TopBrands} from './Brands/topBrands'
export {default as Login} from './Login/Login'
export {default as SignUp} from '../Pages/SignUp/SignUp'
export {default as Bids} from '../Pages/Bids/Bids'
export {default as Chatroom} from '../Pages/Chatroom/Chatroom'
export {default as Checkout} from '../Pages/Checkout/Checkout'
export {default as Support} from './CustomerSupport/CustomerSupport'
export {default as RecentlySold} from './RecentlySold/RecentlySold'
export {default as Profile} from './Profile/ProfilePage'