export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_USER_INFO = "GET_USER_INFO";
export const ADD_TO_CART = "ADD_TO_CART";
export const UPDATE_CART_QUANTITY = "UPDATE_CART_QUANTITY";
export const TOGGLE_CART = "TOGGLE_CART";
export const ADD_AUCTION = "ADD_AUCTION";